title: ThoHi's Website
description: Personal website showcasing projects, thoughts, and experiences in technology and data science.
baseurl: ""
url: "https://thohi.github.io"

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Site settings
author:
  name: ThoHi
  email: ye50351@gmail.com
  url: https://thohi.github.io

# Social links
github_username: ThoHi
# linkedin_username: your-linkedin
# twitter_username: your-twitter

# Build settings
permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .jekyll-cache/
  - _site/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Optional: Add other configurations as needed
# markdown: kramdown
# permalink: /:year/:month/:day/:title/
