title: ThoHi's Website
description: My personal website
baseurl: ""
url: "https://thohi.github.io"
github_username: ThoHi

# Build settings
markdown: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
author:
  name: ThoHi
  email: ye50351@gmail.com

# Social links
# linkedin_username: your-linkedin
# twitter_username: your-twitter

# Build settings
permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Optional: Add other configurations as needed
# markdown: kramdown
# permalink: /:year/:month/:day/:title/
