title: ThoHi's Website
description: Personal website showcasing projects, thoughts, and experiences in technology and data science.
baseurl: ""
url: "https://thohi.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Header pages for navigation
header_pages:
  - about.md
  - projects.html

# Site settings
author:
  name: ThoHi
  email: ye50351@gmail.com

# Social links
github_username: ThoHi
# linkedin_username: your-linkedin
# twitter_username: your-twitter

# Build settings
permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .jekyll-cache/
  - _site/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
