title: ThoHi's Website
description: My personal website
domain: thohi.github.io
url: https://thohi.github.io
baseurl: ""

# Build settings
markdown: GFM
theme: minima
safe: true
lsi: false
incremental: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
author:
  name: ThoHi
  email: ye50351@gmail.com

# Social links
# linkedin_username: your-linkedin
# twitter_username: your-twitter

# Build settings
permalink: /blog/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .github
  - .gitignore
  - .ruby-version

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Optional: Add other configurations as needed
# markdown: kramdown
# permalink: /:year/:month/:day/:title/
